### PR TITLE
move --workdir to  --tempdir and --save-workdir

### PR DESCRIPTION
**Pull request by ircwaves**
@matthewhanson and I spoke about this idea, the context of the cirrus Task class, but as this is starting fresh, thought now would be a good time.  `--workdir` has the duality of specifying location for temporaries, and implicitly that you don't want to delete that directory.  To make things more explicit, we can split that into two as:
+ `--tempdir` as location where `_workdir` will be created.
+ `--save-workdir` to explicitly avert `_workdir` deletion.

Another benefit of `--save-workdir` is that if you don't care where the dir gets created, it gives you what you want.  

## Question:
Are there other use-cases of `--workdir` that I'm missing here?  I suppose we could support `--workdir` by having that imply `self._workdir=args.workdir` and `--save-workdir`.

### CODE REVIEW

**Comment by ircwaves** [comment]
The other alternative implementation was using an env var (`DEBUG_STAC_TASK` or such) to control the `workdir` deletion.

**Comment by gadomski** [comment]
> --tempdir as location where _workdir will be created.

A tmpdir that didn't get deleted feels strange.

> Another benefit of --save-workdir is that if you don't care where the dir gets created, it gives you what you want.

How would the user learn where the files were created? Disclaimer: I haven't looked at the code before asking this question, I'm on my phone.

> The other alternative implementation was using an env var (DEBUG_STAC_TASK or such) to control the workdir deletion.

I tend to be anti-envvar, unless that envvar is linked into a config object that can also be controlled with flags (and config files).

**Comment by matthewhanson** [comment]
I think it makes sense to split these into two and be explicit about it.

However, not really liking the 'tempdir' name, as it implies it is temporary, and isn't clear it's the same dir as what is referred to as '--save-workdir'.   I think these should use the same term at least, so either  `tempdir` and `save_tempdir`, or (better in my opinion), `workdir` and `save_workdir`.

**Comment by ircwaves** [comment]
I'm going to address the comments here after #3 is merged/closed, as the updates there seem more important.

**Comment by matthewhanson** [comment]
OBE, addition of save_workdir param on main

**Pull request closed without merging**
